# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/autonomous_driving',
                'doc_host': 'https://svelascodimate.github.io',
                'git_url': 'https://github.com/svelascodimate/autonomous_driving',
                'lib_path': 'autonomous_driving'},
  'syms': {'autonomous_driving.core': {'autonomous_driving.core.foo': ('core.html#foo', 'autonomous_driving/core.py')}}}